name: Flake8 Lint

on: [push, pull_request]

permissions: read-all

jobs:
  Ambient_Light_Detector:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Ambient Light Detector
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --exclude=.venv --statistics